apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::596741057763:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K535TCXBEYHS
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::596741057763:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-16T05:42:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1719"
  uid: 5c146b43-04b7-4349-9bff-400f1ec13d11
